fix #1
codeclassroom/PlagCheck pull request #2
Opened 2019-10-21 19:33 UTC by vhsw

Sorry, I went a little bit crazy refactoring this. But you can get an idea of how to fix the bug described in #1

2019-10-22 09:04 UTC, Bhupesh-V commented
@vhsw  your PR helped me a lot :rocket: 
But I can't merge these changes beause you are using Python 3.8 and I  have developed this in Python 3.6 so the type hints won't work or will they :confused:

2019-10-23 10:43 UTC, vhsw commented
Type hints were added in Python 3.5, so this code should work fine in Python 3.6
I added [Travis CI](https://travis-ci.org/vhsw/PlagCheck/) with some tests to make sure everything works

2019-10-24 06:16 UTC, Bhupesh-V requested changes
Removing the following lines from `deno.py` will give `USER_ID` error
```python
from dotenv import load_dotenv
load_dotenv()
````

Also are you using `pytest` for running tests ?

2019-10-24 06:19 UTC, Bhupesh-V commented on plagcheck/plagcheck_test.py
> +from plagcheck import plagcheck
```suggestion
import plagcheck
```

2019-10-24 06:20 UTC, Bhupesh-V commented on demo.py
> +from plagcheck import plagcheck
```suggestion
from plagcheck import plagcheck
from dotenv import load_dotenv
load_dotenv()
```

2019-10-24 06:29 UTC, Bhupesh-V commented
> Type hints were added in Python 3.5, so this code should work fine in Python 3.6

Oh ! ok wasn't aware of that, thanks :+1:

2019-11-02 07:01 UTC, merged

2019-11-02 07:52 UTC, Bhupesh-V commented
@all-contributors please add @vhsw for code, bug, test